[Startup]
AppName=Instal-therm 4.5 HCR \ heat&energy 4.5 Hepworth HU
ProductGUID=3BFAD315-07CF-4119-BB8A-F8EBBBCC8D8E
CompanyName=Hepworth
CompanyURL=http://instalsoft.com
ErrorReportURL=http://www.installshield.com/isetup/ProErrorCentral.asp?ErrorCode=%d : 0x%x&ErrorInfo=%s
MediaFormat=1
LogMode=1
Skin=setup.isn
Resource=_Setup.dll
SmallProgress=Y
SplashTime=5
CheckMD5=Y
CmdLine=
ShowPasswordDialog=N
EngineVersion=12.0.0.49974
EngineBinding=1
[Languages]
Default=0x000e
count=1
key0=0x000e
