[Startup]
AppName=Hepworth 4.5 HU Update manager
ProductGUID=EEDDD9A6-1A29-432F-B613-A4CE1AB1CE09
CompanyName=Hepworth
ErrorReportURL=http://www.installshield.com/isetup/ProErrorCentral.asp?ErrorCode=%d : 0x%x&ErrorInfo=%s
MediaFormat=1
LogMode=1
Skin=setup.isn
Resource=_Setup.dll
SmallProgress=N
SplashTime=5
CheckMD5=Y
CmdLine=
ShowPasswordDialog=N
EngineVersion=12.0.0.49974
EngineBinding=1
[Languages]
Default=0x000e
count=1
key0=0x000e
